domain_path: /home/thebu/newhome/vivado_insanity/refactor_jan27/vitis_project/platform/export/platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /opt/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
